### ISSUE TITLE
[FEATURE] Add `solhint` hook to the pre-commit

### ISSUE THREAD

**Issue by ReznikovRoman** [neuromaxer/bab#2]
**Description**
Add solhint linter to the pre-commit hooks

**Possible solution**
1. Add `solhint` linter to `husky` or `pre-commit`

**Additional context**
- [pre-commit docs](https://pre-commit.com/#node)
- [husky docs](https://github.com/typicode/husky#usage)

**Comment by neuromaxer** [comment]
Apparently you need to have a `.pre-commit-hooks.yaml` file in a repo you want to get a pre-commit hook from. Since solhint does not have such a file it is not possible to make it part of pre-commit hooks. Therefore, we have to resort to husky
